  version: '3.8'
  networks:
    mynetwork:
      driver: bridge

  x-logging: &logging
    logging:
      driver: loki
      mode: non-blocking
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

  services:

    notifier:
      networks:
        - mynetwork
      build:
        context: ./notifier
        dockerfile: Dockerfile
      container_name: Notifier
      ports:
        - "8082:8082"
      volumes:
        - /home/umut/goKripto/notifier:/app

    zookeeper:
      networks:
        - mynetwork
      image: wurstmeister/zookeeper
      container_name: Zookeeper
      ports:
        - "2181:2181"

    kafka:
      networks:
        - mynetwork
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        
    go-app:
      networks:
        - mynetwork
      build:
        context: ./crypto
        dockerfile: Dockerfile
      container_name: Kripto-app
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      command: air ./crypto/main.go
      volumes:
        - ./crypto:/app


    postgres:
      networks:
        - mynetwork
      image: postgres:15.0
      container_name: Kripto-Postgres
      environment:
        POSTGRES_DB: kriptoDB
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 393406
      ports:
        - "5435:5432"
      volumes:
        - postgres-db:/var/lib/postgresql/data

    prometheus:
      networks:
        - mynetwork
      image: prom/prometheus:v2.40.4
      container_name: Prometheus
      ports:
        - 9090:9090
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
      networks:
        - mynetwork
      image: grafana/grafana:latest
      container_name: Grafana
      ports:  
        - 3000:3000
      volumes:
        - ./:/goKripto/datasources.yml

    # Kafka testleri yapılasıya kadar devre dışı bırakıldı
    # docker compose'da container'ı downlamaya çalışıldığında yaklaşık olarak 6 dakika bekletiyor
    # bundan dolayı kapalı

    # loki:
    #   networks:
    #     - mynetwork
    #   image: grafana/loki:2.9.0
    #   container_name: Loki
    #   volumes:
    #     - /home/umut/goKripto/loki-config.yml:/etc/loki/local-config.yml   
    #   ports:
    #     - "3100:3100"
    #   command: -config.file=/etc/loki/local-config.yml 

    # promtail:
    #   networks:
    #     - mynetwork
    #   image: grafana/promtail:2.9.0
    #   container_name: Promtail
    #   volumes:
    #     - /var/log:/var/log
    #     - /var/lib/docker/containers:/var/lib/docker/containers
    #     - /home/umut/goKripto/promtail-config.yml:/etc/promtail/promtail-config.yml   
    #   restart: unless-stopped
    #   command: -config.file=/etc/promtail/promtail-config.yml
  
  volumes:
    grafana:
    postgres-db: