version: '3.8'

services:
  go-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Kripto-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: air ./main.go -b 0.0.0.0
    volumes:
      - ./:/app


  postgres:
    image: postgres:latest
    container_name: Kripto-Postgres
    environment:
      POSTGRES_DB: kriptoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 393406
    ports:
      - "5435:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data


  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./:/goKripto/prometheus.yml


  grafana:
    image: grafana/grafana
    ports:  
      - 3000:3000
    volumes:
      - ./:/goKripto/datasources.yml



volumes:
  grafana:
  postgres-db: