global:
  scrape_interval:     10s 
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'my-service-name'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['go-app:8080'] 


  