apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out /home/umut/goKripto/kubernetes
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: go-app
  name: go-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: go-app
status:
  loadBalancer: {}
