apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: blrumutcan/cryptoapp:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app
        - name: go-app-volume
      volumes:
      - name: go-app-volume
        hostPath:
          path: /home/umut/goKripto/crypto

--- 

apiVersion: v1
kind: Service
metadata:
  name: go-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector: 
    app: go-app
  ports:
    - port: 8080
      targetPort: 8080