apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out /home/umut/goKripto/kubernetes
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: notifier
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notifier
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out /home/umut/goKripto/kubernetes
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/gokripto-mynetwork: "true"
        io.kompose.service: notifier
    spec:
      containers:
        - image: notifier
          name: notifier
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: notifier-claim0
      restartPolicy: Always
      volumes:
        - name: notifier-claim0
          persistentVolumeClaim:
            claimName: notifier-claim0
status: {}
