apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: blrumutcan/notifier/:firsttry # Notifier'ı docker'a pushla 
          ports:
            - containerPort: 8082
          volumeMounts:
            - mountPath: /app
            - name: notifier-volume
      volumes:
      - name: notifier-volume
      hostPath:
        path: /home/umut/goKripto/notifier

---

apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: notifier
  ports:
      port: 8082
      targetPort: 8082 
