apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: your-docker-image-name # Bu imaj adını Dockerfile ve Docker Hub gibi kaynaklara göre güncellemeniz gerekebilir.
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: notifier-volume
              mountPath: /app
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer # Service türünü uygulamanızın gereksinimlerine göre ayarlayabilirsiniz.
