apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out /home/umut/goKripto/kubernetes
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out /home/umut/goKripto/kubernetes
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/gokripto-mynetwork: "true"
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/promtail-config.yml
          image: grafana/promtail:latest
          name: promtail
          resources: {}
          volumeMounts:
            - mountPath: /var/log
              name: promtail-claim0
            - mountPath: /var/lib/docker/containers
              name: promtail-claim1
            - mountPath: /etc/promtail/promtail-config.yml
              name: promtail-claim2
      restartPolicy: Always
      volumes:
        - name: promtail-claim0
          persistentVolumeClaim:
            claimName: promtail-claim0
        - name: promtail-claim1
          persistentVolumeClaim:
            claimName: promtail-claim1
        - name: promtail-claim2
          persistentVolumeClaim:
            claimName: promtail-claim2
status: {}
